/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author 91630
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertStudent = new javax.swing.JButton();
        insertResult = new javax.swing.JButton();
        listStudent = new javax.swing.JButton();
        listResult = new javax.swing.JButton();
        updateResult = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertStudent.setText("Insert Student");
        insertStudent.setPreferredSize(new java.awt.Dimension(50, 40));
        insertStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertStudentActionPerformed(evt);
            }
        });
        getContentPane().add(insertStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 30));

        insertResult.setText("InsertResult");
        insertResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertResultActionPerformed(evt);
            }
        });
        getContentPane().add(insertResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, -1));

        listStudent.setText("List Student");
        listStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentActionPerformed(evt);
            }
        });
        getContentPane().add(listStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, -1));

        listResult.setText("List Student Result");
        listResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listResultActionPerformed(evt);
            }
        });
        getContentPane().add(listResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, -1));

        updateResult.setText(" Update Student Marks");
        updateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResultActionPerformed(evt);
            }
        });
        getContentPane().add(updateResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(550, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(550, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertStudentActionPerformed
        // TODO add your handling code here:
        InsertStudent frame=new InsertStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertStudentActionPerformed

    private void insertResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertResultActionPerformed
        // TODO add your handling code here:
        InsertResult frame=new InsertResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertResultActionPerformed

    private void listStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentActionPerformed
        // TODO add your handling code here:
        ListStudents frame=new ListStudents();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_listStudentActionPerformed

    private void listResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listResultActionPerformed
        // TODO add your handling code here:
        ListResults frame=new ListResults();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_listResultActionPerformed

    private void updateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResultActionPerformed
        // TODO add your handling code here:
        UpdateResult frame=new UpdateResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_updateResultActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(null,"Are you sure you want to exit","Submit",JOptionPane.YES_NO_OPTION);
        
        if(response==0){
            setVisible(false);
            Home frame=new Home();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insertResult;
    private javax.swing.JButton insertStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listResult;
    private javax.swing.JButton listStudent;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton updateResult;
    // End of variables declaration//GEN-END:variables
}
